### ISSUE TITLE
Downloading by tag

### ISSUE THREAD

**Issue by Zumbalamambo** [Denisolt/flickr_album_downloader#1]
How do I download all images from tag

**Comment by Denisolt** [comment]
It doesn't have that functionality, but I can code it if you want to

**Comment by Zumbalamambo** [comment]
Yes please sir.. thank you so much in advance..

**Comment by Denisolt** [comment]
Hey, so added the download by a tag. On flickrs website it says they allow 4,000 requests. Haven't tested it, so lmk if you run into another problem. 
when you search by tags, make sure you write the tags in format of:tag1,tag2,tag3 and so on.
